var models = require("./models/index")

let User = models.User



User.bulkCreate([
    {firstName: "Caro",
    lastName: "Querida",
    email: "caro@hot.com",
    address1: "castillo",
    address2: "1332",
    address3: "caba",
    postCode: "1416",
    phone: "0303456",
    rol_id: "superAdmin",
    password: "saynomore",},

    {firstName: "Tefo",
    lastName: "Querido",
    email: "tefo@hot.com",
    address1: "castillo",
    address2: "1332",
    address3: "caba",
    postCode: "1416",
    phone: "0303456",
    rol_id: "superAdmin",
    password: "saynomore",},

    {firstName: "Alex",
    lastName: "Querido",
    email: "alex@hot.com",
    address1: "castillo",
    address2: "1332",
    address3: "caba",
    postCode: "1416",
    phone: "0303456",
    rol_id: "superAdmin",
    password: "saynomore",},

    {firstName: "Santi",
    lastName: "Querido",
    email: "santi@hot.com",
    address1: "castillo",
    address2: "1332",
    address3: "caba",
    postCode: "1416",
    phone: "0303456",
    rol_id: "superAdmin",
    password: "saynomore",},

    {firstName: "Agus",
    lastName: "Salame",
    email: "agus@hot.com",
    address1: "castillo",
    address2: "1332",
    address3: "caba",
    postCode: "1416",
    phone: "0303456",
    rol_id: "superAdmin",
    password: "saynomore",},

    {firstName: "Chiqui",
    lastName: "Charly",
    email: "chiqui@hot.com",
    address1: "castillo",
    address2: "1332",
    address3: "caba",
    postCode: "1416",
    phone: "0303456",
    rol_id: "client",
    password: "saynomore",},

    {firstName: "Pepe",
    lastName: "Grillo",
    email: "pepe@hot.com",
    address1: "castillo",
    address2: "1332",
    address3: "caba",
    postCode: "1416",
    phone: "0303456",
    rol_id: "client",
    password: "saynomore",},

    {firstName: "Viko",
    lastName: "Rama",
    email: "rama@hot.com",
    address1: "castillo",
    address2: "1332",
    address3: "caba",
    postCode: "1416",
    phone: "0303456",
    rol_id: "client",
    password: "saynomore",},

    {firstName: "Cande",
    lastName: "Kndnt",
    email: "cande@hot.com",
    address1: "castillo",
    address2: "1332",
    address3: "caba",
    postCode: "1416",
    phone: "0303456",
    rol_id: "admin",
    password: "saynomore",},
   
])

