// Users
export const RECEIVE_MOVIES = 'RECEIVE_MOVIES';
export const RECEIVE_MOVIE = 'RECEIVE_MOVIE';

// Products
export const RECEIVE_SERIES = 'RECEIVE_SERIES';
export const RECEIVE_SERIE = 'RECEIVE_SERIE';

//Search
export const RECEIVE_SEARCH = 'RECEIVE_SEARCH';
export const RECEIVE_SEARCHINDIVIDUAL = 'RECEIVE_SEARCHINDIVIDUAL';

